package com.inflames1986.janweatherkotlin.utils

const val KEY_BUNDLE_WEATHER = "weather"
const val YANDEX_DOMAIN = "https://api.weather.yandex.ru/"
const val YANDEX_DOMAIN_HARD_MODE = "http://212.86.114.27/"
const val YANDEX_PATH = "v2/informers?"
const val YANDEX_API_KEY = "X-Yandex-API-Key"
const val KEY_BUNDLE_LAT = "lat1"
const val KEY_BUNDLE_LON = "lon1"
const val KEY_BUNDLE_SERVICE_MESSAGE ="kbsm"
const val KEY_BUNDLE_SERVICE_BROADCAST_WEATHER = "kbsbw"
const val KEY_WAVE_SERVICE_BROADCAST = "kwsb"
const val KEY_ERROR_SERVICE_MESSAGE = "kesm"
const val KEY_ERROR_MESSAGE = "kem"
const val KEY_WAVE_ERROR_BROADCAST = "kweb"
